services:
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   container_name: frontend
  #   ports:
  #     - "5173:5173"
  #   networks:
  #     - dev

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    depends_on:
      - db
      - redis
    networks:
      - dev
    ports:
      - "8000:8000"

  db:
    image: postgres:14
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=hardpassword228
      - POSTGRES_DB=mamonts-scam
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./db-config/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./db-config/pg_hba.conf:/etc/postgresql/pg_hba.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    networks:
      - dev
    ports:
      - "5432:5432"

volumes:
  postgres-data:

networks:
  dev:
    driver: bridge
